#define JAM_OR_OR                           1
#define JAM_OR                              2
#define JAM_AND_AND                         3
#define JAM_AND                             4
#define JAM_EQ                              5
#define JAM_NEQ                             6
#define JAM_IN                              7
#define JAM_LT                              8
#define JAM_LE                              9
#define JAM_GT                             10
#define JAM_GE                             11
#define JAM_NOT                            12
#define JAM_LOCAL                          13
#define JAM_EOM                            14
#define JAM_LPAREN                         15
#define JAM_RPAREN                         16
#define JAM_LBRACE                         17
#define JAM_RBRACE                         18
#define JAM_INCLUDE                        19
#define JAM_ARG                            20
#define JAM_ON                             21
#define JAM_RETURN                         22
#define JAM_FOR                            23
#define JAM_SWITCH                         24
#define JAM_IF                             25
#define JAM_MODULE                         26
#define JAM_CLASS                          27
#define JAM_WHILE                          28
#define JAM_ELSE                           29
#define JAM_RULE                           30
#define JAM_OM                             31
#define JAM_ACTIONS                        32
#define JAM_STRING                         33
#define JAM_PLUS_EQ                        34
#define JAM_OPT_EQ                         35
#define JAM_DEFAULT                        36
#define JAM_CASE                           37
#define JAM_COLON                          38
#define JAM_LBRACKET                       39
#define JAM_RBRACKET                       40
#define JAM_UPDATED                        41
#define JAM_TOGETHER                       42
#define JAM_IGNORE                         43
#define JAM_QUITELY                        44
#define JAM_PIECEMEAL                      45
#define JAM_EXISTING                       46
#define JAM_BIND                           47
